LOCAL_TIMEZONE='America/New_York'
#REDIS_HOST_NAME='revan'
REDIS_HOST_NAME='localhost'
REDIS_SET_NAME='energymon_set'
REDIS_HASH_NAME='energymon_hash'
SQLITE_DATABASE_PATH='/home/clinstid/src/energymon/energymon.sqlite3'
